### ISSUE TITLE
VDM Translator XML Marshalling Error: JAXB jakarta/activation/DataSource

### ISSUE THREAD

**Issue by chrisage** [ge-high-assurance/VERDICT#277]
**Describe the bug**
VDM xml binding (aadl_in_vdm.xml) throwing error.

```
Exception in thread "Thread-10" java.lang.NoClassDefFoundError: jakarta/activation/DataSource
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl.<clinit>(RuntimeBuiltinLeafInfoImpl.java:463)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeTypeInfoSetImpl.<init>(RuntimeTypeInfoSetImpl.java:31)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:97)
	at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.<init>(ModelBuilder.java:120)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:61)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:405)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:255)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1115)
	at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:144)
	at org.glassfish.jaxb.runtime.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:44)
	at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:368)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:605)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:546)
	at com.ge.verdict.vdm.VdmTranslator.marshalToXml(VdmTranslator.java:31)
	at com.ge.research.osate.verdict.handlers.MBASHandler.runAadl2Csv(MBASHandler.java:146)
	at com.ge.research.osate.verdict.handlers.MBASHandler$1.run(MBASHandler.java:96)
Caused by: java.lang.ClassNotFoundException: jakarta.activation.DataSource cannot be found by com.ge.research.osate.verdict_1.0.0.202206211419
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 16 more
```

**To Reproduce**
1. Open OSATE
2. Update VERDICT drivers to the latest version (1.7.1) (Help -> Check for Updates)
3. Run the MBAA analysis

**Expected behavior**
MBAA is expected to run normally

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 1.7.1

**Additional context**
Possibly a missing dependency to support new functionality:
https://github.com/ge-high-assurance/VERDICT/commit/114433e2b44c1c37f827e819348bc7fa2c4ca897#diff-8a7ec1031ed404eee878a5afc15c7db34618a6daa129fb5ded3da7d9e1bb31a1R146

**Comment by chrisage** [comment]
Culprit was a dependabot major version update of jaxb @ https://github.com/ge-high-assurance/VERDICT/commit/60789470fd253c4e214ce2c2bfe31a71c1844a30
